### ISSUE TITLE
Skip boot mode

### ISSUE THREAD

**Issue by nicjensen** [magic-blue-smoke/Raspberry-Pi-CM4-TV-Stick#2]
How do I flash the emmc on this board? I've tried moving the switch to "C" position on the board and connecting USB-C cable directly to the computer. Nothing happends on RPI-Boot? Should I add another usb cable to Usb-A...?

**Comment by magic-blue-smoke** [comment]
Hi @nicjensen

To flash CM4 eMMC you’d need:
- set TV Stick slide switch to USB-C position
- disable CM4 eMMC boot by holding down TV Stick button while powering it. Apart from GPIO, this button also tied to RPInBOOT pin, which sampled at power-on. This also means you can release the button after connecting USB-C cable
- now CM4 is waiting for Raspberry Pi `usbboot` firmware which would make eMMC to appear as mass storage device in your system. Jeff Geerling did nice job documenting this [in his blog](https://www.jeffgeerling.com/blog/2020/how-flash-raspberry-pi-os-compute-module-4-emmc-usbboot)
- now use your favorite imager to flash eMMC, just like you’re flashing SD card for Raspberry Pi

Important: your PC should be able to provide sufficient current for CM4, also make sure to use known good cable, capable to power CM4

**Comment by nicjensen** [comment]
Holding down the button did the trick. Thanks for your help!
